"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    draftsharks.com API (draftsharks_com_api)
ID:     8cbb56cd-270c-41c6-ab5b-ff713cf1ef13
Engine: parse_sdk 0.2.0
Generated at: 2026-07-22T15:52:11.627683+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Depth(str, enum.Enum):
    ANALYSIS = 'analysis'
    RANKINGS = 'rankings'


class Scoring(str, enum.Enum):
    PPR = 'ppr'
    NON_PPR = 'non-ppr'
    HALF_PPR = 'half-ppr'


class IsDynasty(str, enum.Enum):
    TRUE = 'true'
    FALSE = 'false'

    @property
    def display(self) -> str:
        return _DISPLAYS_IsDynasty.get(self.name, self.name)

_DISPLAYS_IsDynasty = {
    'TRUE': 'true',
    'FALSE': 'false',
}


class LeagueType(str, enum.Enum):
    STANDARD = 'standard'
    SUPERFLEX = 'superflex'


class SosPosition(str, enum.Enum):
    K = 'k'
    QB = 'qb'
    RB = 'rb'
    TE = 'te'
    WR = 'wr'


class ResourceNotFound(_ParseError):
    """
    Player ID or team slug does not exist (404/410 from upstream)
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'player_id': 'player_id'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, player_id: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.player_id = player_id


class Team(_Resource):
    id: int
    bye: int
    abbr: str
    schedule: List[Matchup]
    _RESOURCE_NAME = 'Team'
    _KEY_FIELD = 'id'

class Player(_Resource):
    id: str
    adp: str
    bye: str
    sos: str
    name: str
    rank: str
    team: str
    floor: str
    games: str
    ceiling: str
    ds_value: str
    position: str
    consensus: str
    is_rookie: bool
    injury_risk: str
    tier_overall: str
    ds_projection: str
    tier_positional: str
    _RESOURCE_NAME = 'Player'
    _KEY_FIELD = 'id'

    def profile(self) -> PlayerProfile:
        """
        Fetch full player profile details including bio, weekly projections, season projections, consensus projections, scoring configurations, and dynasty trade values. Requires the player's numeric ID.
        """
        _params: Dict[str, Any] = {}
        _params['player_id'] = self.id
        
        _resp = self._api._request('GET', 'get_player_profile', _params)
        return _coerce(_resp, 'PlayerProfile', self, mode='return')

class Article(_Resource):
    date: str
    link: str
    title: str
    player: Optional[ArticlePlayer]
    summary: str
    _RESOURCE_NAME = 'Article'
    _KEY_FIELD = None

class Matchup(_Resource):
    pts: str
    home: int
    week: int
    run_rate: str
    pass_rate: str
    proj_snaps: str
    opponent_team_id: int
    _RESOURCE_NAME = 'Matchup'
    _KEY_FIELD = None

class PlayerBio(_Resource):
    id: int
    height: int
    weight: int
    team_id: int
    birthday: str
    position: str
    last_name: str
    experience: int
    first_name: str
    fantasy_position: str
    _RESOURCE_NAME = 'PlayerBio'
    _KEY_FIELD = None

class DepthChart(_Resource):
    team: str
    sections: List[DepthChartSection]
    _RESOURCE_NAME = 'DepthChart'
    _KEY_FIELD = 'team'

class ArticlePlayer(_Resource):
    name: str
    rank: str
    team: str
    player_id: str
    _RESOURCE_NAME = 'ArticlePlayer'
    _KEY_FIELD = None

class PlayerProfile(_Resource):
    dynasty_analysis: Optional[str]
    playerPageAppVar: PlayerBio
    dynasty_trade_values: Dict[str, str]
    _RESOURCE_NAME = 'PlayerProfile'
    _KEY_FIELD = None

class DepthChartPlayer(_Resource):
    name: str
    player_id: str
    _RESOURCE_NAME = 'DepthChartPlayer'
    _KEY_FIELD = None

class DepthChartSection(_Resource):
    section: str
    positions: List[DepthChartPosition]
    _RESOURCE_NAME = 'DepthChartSection'
    _KEY_FIELD = None

class DepthChartPosition(_Resource):
    players: List[DepthChartPlayer]
    position: str
    _RESOURCE_NAME = 'DepthChartPosition'
    _KEY_FIELD = None

class DraftSharksTeamsCollection(_Collection):
    def list_sos(self, position: Optional[SosPosition | Literal['k', 'qb', 'rb', 'te', 'wr']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Team]:
        """
        Fetch strength-of-schedule data for a given position, including weekly matchups, projected stats, and opponent details for all 32 NFL teams. Returns the current NFL week and full season schedule data.

        Args:
            position: Position to get SOS for.
        """
        _params: Dict[str, Any] = {}
        if position is not None: _params['position'] = position
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_strength_of_schedule', _p)
            items = _extract_items(_resp, 'teamData')
            return ([_coerce(_i, 'Team', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class DraftSharksPlayersCollection(_Collection):
    def list(self, depth: Optional[Depth | Literal['analysis', 'rankings']] = None, scoring: Optional[Scoring | Literal['ppr', 'non-ppr', 'half-ppr']] = None, position: Optional[str] = None, is_dynasty: Optional[IsDynasty | Literal['true', 'false']] = None, league_type: Optional[LeagueType | Literal['standard', 'superflex']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Player]:
        """
        Fetch the player rankings table for a given scoring format and league type. Returns up to 500 players with projections, ADP, injury risk, and tier information. Paginates as a single page. Some parameter combinations (e.g. dynasty + analysis + non-ppr) may not be supported upstream and will return an upstream error.

        Args:
            depth: Research depth.
            scoring: Scoring format.
            position: Filter by position: 'QB', 'RB', 'WR', 'TE', or empty string for all positions.
            is_dynasty: Set to 'true' for dynasty rankings, 'false' for redraft.
            league_type: League type.
        """
        _params: Dict[str, Any] = {}
        if depth is not None: _params['depth'] = depth
        if scoring is not None: _params['scoring'] = scoring
        if position is not None: _params['position'] = position
        if is_dynasty is not None: _params['is_dynasty'] = is_dynasty
        if league_type is not None: _params['league_type'] = league_type
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_rankings', _p)
            items = _extract_items(_resp, 'players')
            return ([_coerce(_i, 'Player', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class DraftSharksArticlesCollection(_Collection):
    def list(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Article]:
        """
        Fetch recent fantasy football news articles with summaries and related player information from DraftSharks. Returns the latest articles available on the news page, typically 20 items.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_news_articles', _p)
            items = _extract_items(_resp, 'articles')
            return ([_coerce(_i, 'Article', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class DraftSharksDepthChartsCollection(_Collection):
    def get(self, team_slug: Optional[str] = None) -> DepthChart:
        """
        Fetch team depth charts showing player positions and depth order for offense, defense, and special teams. Each position lists players from starter to backup in order.

        Args:
            team_slug: Team URL slug (e.g. 'buffalo-bills', 'kansas-city-chiefs').
        """
        _params: Dict[str, Any] = {}
        if team_slug is not None: _params['team_slug'] = team_slug
        
        _resp = self._api._request('GET', 'get_depth_charts', _params)
        return _coerce(_resp, 'DepthChart', self, mode='return')

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Team': Team,
    'Player': Player,
    'Article': Article,
    'Matchup': Matchup,
    'PlayerBio': PlayerBio,
    'DepthChart': DepthChart,
    'ArticlePlayer': ArticlePlayer,
    'PlayerProfile': PlayerProfile,
    'DepthChartPlayer': DepthChartPlayer,
    'DepthChartSection': DepthChartSection,
    'DepthChartPosition': DepthChartPosition,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class DraftSharks(_BaseAPI):
    """
    Scraper for DraftSharks.com fantasy football data including rankings, player profiles, strength of schedule, depth charts, and news.
    """
    SCRAPER_ID: ClassVar[str] = '8cbb56cd-270c-41c6-ab5b-ff713cf1ef13'
    PINNED_VERSION: ClassVar[Optional[int]] = 9
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': ResourceNotFound}

    @property
    def teams(self) -> 'DraftSharksTeamsCollection':
        return DraftSharksTeamsCollection(_api=self, _parent=None)

    @property
    def players(self) -> 'DraftSharksPlayersCollection':
        return DraftSharksPlayersCollection(_api=self, _parent=None)

    @property
    def articles(self) -> 'DraftSharksArticlesCollection':
        return DraftSharksArticlesCollection(_api=self, _parent=None)

    @property
    def depth_charts(self) -> 'DraftSharksDepthChartsCollection':
        return DraftSharksDepthChartsCollection(_api=self, _parent=None)

__all__ = [
    'DraftSharks',
    'Team',
    'Player',
    'Article',
    'Matchup',
    'PlayerBio',
    'DepthChart',
    'ArticlePlayer',
    'PlayerProfile',
    'DepthChartPlayer',
    'DepthChartSection',
    'DepthChartPosition',
    'Depth',
    'Scoring',
    'IsDynasty',
    'LeagueType',
    'SosPosition',
    'ResourceNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
