# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
"""Walkthrough: DraftSharks SDK — fantasy football rankings, profiles, depth charts."""
from parse_apis.draftsharks_com_api import (
    DraftSharks, Scoring, LeagueType, SosPosition, Depth, ResourceNotFound
)

client = DraftSharks()

# List top QB rankings in half-PPR superflex format
for player in client.players.list(scoring=Scoring.HALF_PPR, league_type=LeagueType.SUPERFLEX, position="QB", depth=Depth.RANKINGS, limit=5):
    print(player.name, player.adp, player.ds_projection, player.injury_risk)

# Drill into a single player's full profile
top_player = client.players.list(scoring=Scoring.PPR, position="QB", limit=1).first()
if top_player:
    prof = top_player.profile()
    bio = prof.bio
    print(bio.first_name, bio.last_name, bio.position, bio.height, bio.weight)

# Strength of schedule for wide receivers
for team in client.teams.list_sos(position=SosPosition.WR, limit=3):
    print(team.abbr, team.bye, len(team.schedule))

# Fetch a specific team's depth chart
chart = client.depth_charts.get(team_slug="kansas-city-chiefs")
for section in chart.sections:
    for pos in section.positions:
        print(section.section, pos.position, [p.name for p in pos.players])

# Typed error handling — profile() raises ResourceNotFound for invalid IDs
if top_player:
    try:
        prof = top_player.profile()
        print(prof.bio.first_name, prof.bio.last_name)
    except ResourceNotFound as exc:
        print(f"Player not found: {exc.player_id}")

# Latest fantasy news
for article in client.articles.list(limit=3):
    print(article.title, article.link)

print("exercised: players.list / player.profile / teams.list_sos / depth_charts.get / articles.list")
