"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    ESPN Sports Data API (espn_sports_data_api)
ID:     1ed7c95b-0348-41fb-baa1-f5f0096b7da5
Engine: parse_sdk 0.2.0
Generated at: 2026-07-22T15:52:11.625944+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class League(str, enum.Enum):
    F1 = 'f1'
    MLB = 'mlb'
    MLC = 'mlc'
    MLS = 'usa.1'
    NBA = 'nba'
    NFL = 'nfl'
    NHL = 'nhl'
    NLL = 'nll'
    UFC = 'ufc'
    WNBA = 'wnba'
    NASCAR = 'nascar'
    LA_LIGA = 'esp.1'
    LIGUE_1 = 'fra.1'
    SERIE_A = 'ita.1'
    BUNDESLIGA = 'ger.1'
    PREMIER_LEAGUE = 'eng.1'
    CHAMPIONS_LEAGUE = 'uefa.champions'
    COLLEGE_BASEBALL = 'college-baseball'
    COLLEGE_FOOTBALL = 'college-football'
    COLLEGE_SOFTBALL = 'college-softball'
    MENS_COLLEGE_BASKETBALL = 'mens-college-basketball'
    WOMENS_COLLEGE_BASKETBALL = 'womens-college-basketball'


class SearchType(str, enum.Enum):
    TEAM = 'team'
    PLAYER = 'player'


class ResourceNotFound(_ParseError):
    """
    The requested athlete or team ID does not exist in the specified league (404 response)
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'athlete_id': 'athlete_id'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, athlete_id: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.athlete_id = athlete_id


class Team(_Resource):
    id: str
    logo: str
    name: str
    color: str
    links: Dict[str, str]
    location: str
    nickname: str
    abbreviation: str
    _RESOURCE_NAME = 'Team'
    _KEY_FIELD = 'id'
    _CONSTRUCTIBLE = True

    @property
    def roster(self) -> 'TeamRosterCollection':
        _stash = getattr(self, '_sub_roster', None)
        if _stash is None:
            _stash = TeamRosterCollection(_api=self._api, _parent=self)
            object.__setattr__(self, '_sub_roster', _stash)
        return _stash

class TeamRosterCollection(_Collection):
    def list(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball'], limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Athlete]:
        """
        Get full roster for a team including player profiles, injuries, and contract details. Each athlete includes biographical info, position, physical attributes, and current status.

        Args:
            league: League identifier.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        _params['team_id'] = self._parent.id
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('POST', 'get_team_roster', _p)
            items = _extract_items(_resp, 'athletes')
            return ([_coerce(_i, 'Athlete', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class Event(_Resource):
    id: str
    date: str
    name: str
    short_name: str
    _RESOURCE_NAME = 'Event'
    _KEY_FIELD = 'id'

class Article(_Resource):
    id: int
    link: Optional[str]
    type: str
    byline: Optional[str]
    premium: bool
    headline: str
    published: str
    description: Optional[str]
    _RESOURCE_NAME = 'Article'
    _KEY_FIELD = 'id'

class Athlete(_Resource):
    id: str
    age: Optional[int]
    name: str
    height: Optional[str]
    jersey: Optional[str]
    status: Optional[str]
    weight: Optional[str]
    headshot: Optional[str]
    position: Optional[str]
    _RESOURCE_NAME = 'Athlete'
    _KEY_FIELD = 'id'
    _CONSTRUCTIBLE = True

    def gamelog(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball'], season: Optional[str] = None) -> AthleteGamelog:
        """
        Get game-by-game stats for an athlete with monthly breakdowns, totals, and averages. Stats labels are sport-specific. Each game includes opponent, result, score, and full stat line.

        Args:
            league: League identifier.
            season: Season year (e.g., 2026). When omitted, returns current season gamelog.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        if season is not None: _params['season'] = season
        _params['athlete_id'] = self.id
        
        _resp = self._api._request('POST', 'get_athlete_gamelog', _params)
        return _coerce(_resp, 'AthleteGamelog', self, mode='return')

    def profile(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball']) -> AthleteProfile:
        """
        Get detailed athlete profile including biographical info, team, injuries, contracts, and status. Returns physical attributes, career timeline, and current team assignment.

        Args:
            league: League identifier.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        _params['athlete_id'] = self.id
        
        _resp = self._api._request('POST', 'get_athlete_profile', _params)
        return _coerce(_resp, 'AthleteProfile', self, mode='return')

    def overview(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball']) -> AthleteOverview:
        """
        Get comprehensive athlete data including season/career stats, fantasy projections, recent news, awards, and expert analysis. Stats labels are sport-specific. Fantasy data may be absent for non-fantasy leagues.

        Args:
            league: League identifier.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        _params['athlete_id'] = self.id
        
        _resp = self._api._request('POST', 'get_athlete_overview', _params)
        return _coerce(_resp, 'AthleteOverview', self, mode='return')

class Standing(_Resource):
    name: str
    entries: List[Dict[str, Any]]
    _RESOURCE_NAME = 'Standing'
    _KEY_FIELD = 'name'

class SearchResult(_Resource):
    id: str
    link: Optional[str]
    name: str
    type: str
    sport: Optional[str]
    league: Optional[str]
    short_name: Optional[str]
    _RESOURCE_NAME = 'SearchResult'
    _KEY_FIELD = 'id'

class AthleteGamelog(_Resource):
    names: List[str]
    labels: List[str]
    display_names: List[str]
    _RESOURCE_NAME = 'AthleteGamelog'
    _KEY_FIELD = None

class AthleteProfile(_Resource):
    id: str
    age: Optional[int]
    name: str
    height: Optional[str]
    jersey: Optional[str]
    weight: Optional[str]
    headshot: Optional[str]
    position: Optional[str]
    last_name: Optional[str]
    debut_year: Optional[int]
    first_name: Optional[str]
    _RESOURCE_NAME = 'AthleteProfile'
    _KEY_FIELD = 'id'

class AthleteOverview(_Resource):
    news: Optional[List[Dict[str, Any]]]
    awards: Optional[List[Dict[str, Any]]]
    fantasy: Optional[Dict[str, Any]]
    rotowire: Optional[Dict[str, Any]]
    statistics: Optional[Dict[str, Any]]
    _RESOURCE_NAME = 'AthleteOverview'
    _KEY_FIELD = None

class ESPNTeamsCollection(_Collection):
    def list(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball'], limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Team]:
        """
        Get all teams for a given league with IDs, names, logos, and links. Returns a complete roster of teams participating in the specified league.

        Args:
            league: League identifier.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('POST', 'get_teams', _p)
            items = _extract_items(_resp, 'teams')
            return ([_coerce(_i, 'Team', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ESPNEventsCollection(_Collection):
    def list(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball'], dates: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Event]:
        """
        Get live scores, final results, and upcoming fixtures for any supported league. Returns match details including scores, venues, broadcasts, leaders, odds, and recaps. Each event includes competitor details with team records, leaders, and broadcasting info.

        Args:
            league: League identifier.
            dates: Date filter in YYYYMMDD format (e.g., 20260424). When omitted, returns current day's events.
        """
        _params: Dict[str, Any] = {}
        if dates is not None: _params['dates'] = dates
        if league is not None: _params['league'] = league
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('POST', 'get_scoreboard', _p)
            items = _extract_items(_resp, 'events')
            return ([_coerce(_i, 'Event', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ESPNArticlesCollection(_Collection):
    def list(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball'], limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Article]:
        """
        Get latest news articles and headlines for a specific league. Returns articles with full metadata including categories, images, and links.

        Args:
            league: League identifier.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('POST', 'get_news', _p)
            items = _extract_items(_resp, 'articles')
            return ([_coerce(_i, 'Article', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ESPNStandingsCollection(_Collection):
    def list(self, league: League | Literal['f1', 'mlb', 'mlc', 'usa.1', 'nba', 'nfl', 'nhl', 'nll', 'ufc', 'wnba', 'nascar', 'esp.1', 'fra.1', 'ita.1', 'ger.1', 'eng.1', 'uefa.champions', 'college-baseball', 'college-football', 'college-softball', 'mens-college-basketball', 'womens-college-basketball'], season: Optional[str] = None, season_type: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Standing]:
        """
        Get current standings/rankings for a league, organized by conference/division with full statistics. Season type '2' returns regular season division breakdown, '3' returns postseason/playoff standings. When omitted, returns summary standings.

        Args:
            league: League identifier.
            season: Season year (e.g., 2026). When omitted, returns current season standings.
            season_type: Season type filter. Use '2' for regular season division breakdown, '3' for postseason/playoff standings. When omitted, returns summary standings.
        """
        _params: Dict[str, Any] = {}
        if league is not None: _params['league'] = league
        if season is not None: _params['season'] = season
        if season_type is not None: _params['season_type'] = season_type
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('POST', 'get_standings', _p)
            items = _extract_items(_resp, 'groups')
            return ([_coerce(_i, 'Standing', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ESPNSearchResultsCollection(_Collection):
    def search(self, query: str, type: Optional[SearchType | str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[SearchResult]:
        """
        Search for athletes and teams across all sports. Returns matching results with IDs for use in other endpoints. When type filter is specified, only results of that type are returned.

        Args:
            query: Search query (player name, team name, etc.)
            type: Filter results by type. Accepted values: 'player', 'team'. When omitted, searches both players and teams.
        """
        _params: Dict[str, Any] = {}
        if type is not None: _params['type'] = type
        if query is not None: _params['query'] = query
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('POST', 'search', _p)
            items = _extract_items(_resp, 'results')
            return ([_coerce(_i, 'SearchResult', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Team': Team,
    'Event': Event,
    'Article': Article,
    'Athlete': Athlete,
    'Standing': Standing,
    'SearchResult': SearchResult,
    'AthleteGamelog': AthleteGamelog,
    'AthleteProfile': AthleteProfile,
    'AthleteOverview': AthleteOverview,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class ESPN(_BaseAPI):
    """
    Comprehensive sports data scraper covering 21+ leagues including NFL, NBA, MLB, NHL, college sports, European soccer, UFC, F1, and more. Provides scores, standings, rosters, player stats, news, and search capabilities.
    """
    SCRAPER_ID: ClassVar[str] = '1ed7c95b-0348-41fb-baa1-f5f0096b7da5'
    PINNED_VERSION: ClassVar[Optional[int]] = 5
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': ResourceNotFound}

    @property
    def teams(self) -> 'ESPNTeamsCollection':
        return ESPNTeamsCollection(_api=self, _parent=None)

    @property
    def events(self) -> 'ESPNEventsCollection':
        return ESPNEventsCollection(_api=self, _parent=None)

    @property
    def articles(self) -> 'ESPNArticlesCollection':
        return ESPNArticlesCollection(_api=self, _parent=None)

    @property
    def standings(self) -> 'ESPNStandingsCollection':
        return ESPNStandingsCollection(_api=self, _parent=None)

    @property
    def search_results(self) -> 'ESPNSearchResultsCollection':
        return ESPNSearchResultsCollection(_api=self, _parent=None)

    def team(self, id: str) -> 'Team':
        return Team(_api=self, id=id)

    def athlete(self, id: str) -> 'Athlete':
        return Athlete(_api=self, id=id)

__all__ = [
    'ESPN',
    'Team',
    'Event',
    'Article',
    'Athlete',
    'Standing',
    'SearchResult',
    'AthleteGamelog',
    'AthleteProfile',
    'AthleteOverview',
    'League',
    'SearchType',
    'ResourceNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
