# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
from parse_apis.espn_sports_data_api import ESPN, League, SearchType

espn = ESPN()

# Search for a player
for result in espn.searchresults.search(query="LeBron James", type=SearchType.PLAYER):
    print(result.name, result.sport, result.league)

# List NBA teams and explore a roster
for team in espn.teams.list(league=League.NBA, limit=5):
    print(team.name, team.abbreviation, team.logo)

# Get a specific team's roster via constructible navigation
lakers = espn.team(id="13")
for player in lakers.roster.list(league=League.NBA):
    print(player.name, player.position, player.jersey)

# Get athlete profile and overview
athlete = espn.athlete(id="1966")
profile = athlete.profile(league=League.NBA)
print(profile.name, profile.position, profile.height, profile.weight)

overview = athlete.overview(league=League.NBA)
print(overview.statistics, overview.rotowire)

# Get game log
gamelog = athlete.gamelog(league=League.NBA, season="2026")
print(gamelog.labels, gamelog.display_names)

# List today's NBA events
for event in espn.events.list(league=League.NBA):
    print(event.name, event.date)

# Get league standings
for group in espn.standings.list(league=League.NBA):
    print(group.name, group.entries)

# Get NBA news articles
for article in espn.articles.list(league=League.NBA, limit=3):
    print(article.headline, article.published, article.premium)
