"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    pro-football-reference.com API (pro_football_reference_com_api)
ID:     68f10b93-1fc8-410d-af5c-7f1b3d6e618d
Engine: parse_sdk 0.2.0
Generated at: 2026-07-22T15:52:11.628929+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Year(str, enum.Enum):
    _2020 = '2020'
    _2021 = '2021'
    _2022 = '2022'
    _2023 = '2023'

    @property
    def display(self) -> str:
        return _DISPLAYS_Year.get(self.name, self.name)

_DISPLAYS_Year = {
    '_2020': '2020',
    '_2021': '2021',
    '_2022': '2022',
    '_2023': '2023',
}


class GameTable(str, enum.Enum):
    PBP = 'pbp'
    VIS_DRIVES = 'vis_drives'
    DRIVE_CHART = 'drive_chart'
    HOME_DRIVES = 'home_drives'

    @property
    def display(self) -> str:
        return _DISPLAYS_GameTable.get(self.name, self.name)

_DISPLAYS_GameTable = {
    'PBP': 'Play-by-Play',
    'VIS_DRIVES': 'Visiting Team Drives',
    'DRIVE_CHART': 'Drive Chart',
    'HOME_DRIVES': 'Home Team Drives',
}


class StatCategory(str, enum.Enum):
    DEFENSE = 'defense'
    KICKING = 'kicking'
    PASSING = 'passing'
    RETURNS = 'returns'
    RUSHING = 'rushing'
    SCORING = 'scoring'
    RECEIVING = 'receiving'


class PlayerNotFound(_ParseError):
    """
    Player ID does not match any player page (404 from upstream)
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'player_id': 'player_id'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, player_id: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.player_id = player_id


class InvalidCategory(_ParseError):
    """
    Stat category is not one of the accepted values
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'category': 'category'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, category: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.category = category


class Game(_Resource):
    loser: str
    to_win: str
    winner: str
    game_id: str
    pts_win: str
    to_lose: str
    gametime: str
    pts_lose: str
    week_num: str
    game_date: str
    yards_win: str
    loser_abbr: str
    yards_lose: str
    winner_abbr: str
    game_location: str
    game_day_of_week: str
    _RESOURCE_NAME = 'Game'
    _KEY_FIELD = 'game_id'
    _CONSTRUCTIBLE = True

    def details(self, table_id: GameTable | Literal['pbp', 'vis_drives', 'drive_chart', 'home_drives']) -> GameDetail:
        """
        Retrieve specific detailed tables for an NFL game such as play-by-play or drive charts. Returns row-level data whose fields vary by table type. Play-by-play includes quarter, down, distance, detail text, and expected points. Drive tables include drive number, start position, plays, yards, and result.

        Args:
            table_id: Table to extract from the game page.
        """
        _params: Dict[str, Any] = {}
        if table_id is not None: _params['table_id'] = table_id
        _params['game_id'] = self.game_id
        
        _resp = self._api._request('GET', 'get_game_details', _params)
        return _coerce(_resp, 'GameDetail', self, mode='return')

    def boxscore(self) -> Boxscore:
        """
        Retrieve detailed boxscore data for a specific NFL game. Returns team scores, game metadata (roof, surface, duration, attendance, Vegas line), and player-level offensive and defensive statistics. The game_id is available from get_season_schedule results.
        """
        _params: Dict[str, Any] = {}
        _params['game_id'] = self.game_id
        
        _resp = self._api._request('GET', 'get_game_boxscore', _params)
        return _coerce(_resp, 'Boxscore', self, mode='return')

class Player(_Resource):
    url: Optional[str]
    name: str
    player_id: str
    _RESOURCE_NAME = 'Player'
    _KEY_FIELD = 'player_id'
    _CONSTRUCTIBLE = True

    def profile(self) -> PlayerProfile:
        """
        Retrieve a player's biographical profile and career stats summary. Returns name, position, college, birthdate, and career statistics tables (passing, rushing, receiving, and/or defense depending on position). The player_id is available from search_players results.
        """
        _params: Dict[str, Any] = {}
        _params['player_id'] = self.player_id
        
        _resp = self._api._request('GET', 'get_player_profile', _params)
        return _coerce(_resp, 'PlayerProfile', self, mode='return')

class Season(_Resource):
    year: str
    _RESOURCE_NAME = 'Season'
    _KEY_FIELD = 'year'
    _CONSTRUCTIBLE = True

    def stats(self, category: StatCategory | Literal['defense', 'kicking', 'passing', 'returns', 'rushing', 'scoring', 'receiving']) -> StatLeaders:
        """
        Retrieve statistical leaders for a given NFL season and category. Returns all qualifying players ranked by the primary stat for that category (e.g. pass_yds for passing, rush_yds for rushing). Fields in each player object vary by category.

        Args:
            category: Stat category to retrieve leaders for.
        """
        _params: Dict[str, Any] = {}
        if category is not None: _params['category'] = category
        _params['year'] = self.year
        
        _resp = self._api._request('GET', 'get_season_stats', _params)
        return _coerce(_resp, 'StatLeaders', self, mode='return')

    def schedule(self) -> Schedule:
        """
        Retrieve the full NFL schedule for a given season. Returns every regular-season and playoff game with final scores, yardage totals, turnover counts, and a game_id suitable for drill-down into boxscores and play-by-play. One request per season; no pagination.
        """
        _params: Dict[str, Any] = {}
        _params['year'] = self.year
        
        _resp = self._api._request('GET', 'get_season_schedule', _params)
        return _coerce(_resp, 'Schedule', self, mode='return')

    def standings(self) -> Standings:
        """
        Retrieve conference standings for a given NFL season. Returns teams grouped by AFC and NFC with wins, losses, points scored/allowed, margin of victory, and strength of schedule metrics.
        """
        _params: Dict[str, Any] = {}
        _params['year'] = self.year
        
        _resp = self._api._request('GET', 'get_season_team_standings', _params)
        return _coerce(_resp, 'Standings', self, mode='return')

class Boxscore(_Resource):
    teams: List[TeamScore]
    defense: List[Dict[str, str]]
    game_id: str
    offense: List[Dict[str, str]]
    game_info: Dict[str, str]
    scoring_summary: List[Dict[str, str]]
    _RESOURCE_NAME = 'Boxscore'
    _KEY_FIELD = 'game_id'

class Schedule(_Resource):
    year: str
    games: List[Game]
    _RESOURCE_NAME = 'Schedule'
    _KEY_FIELD = 'year'

class Standings(_Resource):
    AFC: List[TeamStanding]
    NFC: List[TeamStanding]
    year: str
    _RESOURCE_NAME = 'Standings'
    _KEY_FIELD = 'year'

class TeamScore(_Resource):
    name: str
    score: str
    _RESOURCE_NAME = 'TeamScore'
    _KEY_FIELD = None

class GameDetail(_Resource):
    data: List[Dict[str, str]]
    game_id: str
    table_id: str
    _RESOURCE_NAME = 'GameDetail'
    _KEY_FIELD = 'game_id'

class StatLeaders(_Resource):
    year: str
    stats: List[Dict[str, str]]
    category: str
    _RESOURCE_NAME = 'StatLeaders'
    _KEY_FIELD = 'year'

class TeamStanding(_Resource):
    mov: str
    team: str
    wins: str
    losses: str
    points: str
    sos_total: str
    srs_total: str
    team_abbr: str
    points_opp: str
    points_diff: str
    win_loss_perc: str
    _RESOURCE_NAME = 'TeamStanding'
    _KEY_FIELD = None

class PlayerProfile(_Resource):
    name: str
    college: Optional[str]
    position: Optional[str]
    birthdate: Optional[str]
    player_id: str
    career_defense_stats: Optional[List[Dict[str, str]]]
    career_passing_stats: Optional[List[Dict[str, str]]]
    career_rushing_stats: Optional[List[Dict[str, str]]]
    career_receiving_stats: Optional[List[Dict[str, str]]]
    _RESOURCE_NAME = 'PlayerProfile'
    _KEY_FIELD = 'player_id'

class ProFootballReferenceGamesCollection(_Collection):
    def get(self, game_id: str) -> Game:
        """
        Retrieve detailed boxscore data for a specific NFL game. Returns team scores, game metadata (roof, surface, duration, attendance, Vegas line), and player-level offensive and defensive statistics. The game_id is available from get_season_schedule results.

        Args:
            game_id: Game ID from Pro-Football-Reference (e.g. '202402110kan' for Super Bowl LVIII). Available in get_season_schedule results as game_id.
        """
        _params: Dict[str, Any] = {}
        if game_id is not None: _params['game_id'] = game_id
        
        _resp = self._api._request('GET', 'get_game_boxscore', _params)
        return _coerce(_resp, 'Game', self, mode='return')

class ProFootballReferencePlayersCollection(_Collection):
    def search(self, query: str, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Player]:
        """
        Search for NFL players by name to find their player IDs and profile URLs. If the search matches a single player exactly, PFR redirects to that player's page directly and the result contains one entry. Otherwise returns a list of matching players.

        Args:
            query: Player name to search for (e.g. 'Patrick Mahomes', 'Brady').
        """
        _params: Dict[str, Any] = {}
        if query is not None: _params['query'] = query
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'search_players', _p)
            items = _extract_items(_resp, 'results')
            return ([_coerce(_i, 'Player', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)
    def get(self, player_id: str) -> Player:
        """
        Retrieve a player's biographical profile and career stats summary. Returns name, position, college, birthdate, and career statistics tables (passing, rushing, receiving, and/or defense depending on position). The player_id is available from search_players results.

        Args:
            player_id: Player ID from Pro-Football-Reference (e.g. 'MahoPa00' for Patrick Mahomes). Available from search_players results.
        """
        _params: Dict[str, Any] = {}
        if player_id is not None: _params['player_id'] = player_id
        
        _resp = self._api._request('GET', 'get_player_profile', _params)
        return _coerce(_resp, 'Player', self, mode='return')

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Game': Game,
    'Player': Player,
    'Season': Season,
    'Boxscore': Boxscore,
    'Schedule': Schedule,
    'Standings': Standings,
    'TeamScore': TeamScore,
    'GameDetail': GameDetail,
    'StatLeaders': StatLeaders,
    'TeamStanding': TeamStanding,
    'PlayerProfile': PlayerProfile,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class ProFootballReference(_BaseAPI):
    """
    Access NFL statistics, schedules, standings, game boxscores, play-by-play data, and player profiles from Pro-Football-Reference.com
    """
    SCRAPER_ID: ClassVar[str] = '68f10b93-1fc8-410d-af5c-7f1b3d6e618d'
    PINNED_VERSION: ClassVar[Optional[int]] = 9
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': PlayerNotFound, 'input_format_invalid': InvalidCategory}

    @property
    def games(self) -> 'ProFootballReferenceGamesCollection':
        return ProFootballReferenceGamesCollection(_api=self, _parent=None)

    @property
    def players(self) -> 'ProFootballReferencePlayersCollection':
        return ProFootballReferencePlayersCollection(_api=self, _parent=None)

    def game(self, game_id: str) -> 'Game':
        return Game(_api=self, game_id=game_id)

    def player(self, player_id: str) -> 'Player':
        return Player(_api=self, player_id=player_id)

    def season(self, year: str) -> 'Season':
        return Season(_api=self, year=year)

__all__ = [
    'ProFootballReference',
    'Game',
    'Player',
    'Season',
    'Boxscore',
    'Schedule',
    'Standings',
    'TeamScore',
    'GameDetail',
    'StatLeaders',
    'TeamStanding',
    'PlayerProfile',
    'Year',
    'GameTable',
    'StatCategory',
    'PlayerNotFound',
    'InvalidCategory',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
