# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
from parse_apis.pro_football_reference_com_api import (
    ProFootballReference, StatCategory, GameTable
)

pfr = ProFootballReference()

# Get the 2023 season schedule and find a high-scoring game
schedule = pfr.season("2023").schedule()
for game in schedule.games[:5]:
    print(game.winner, game.pts_win, "-", game.loser, game.pts_lose)

# Get passing leaders for 2023
leaders = pfr.season("2023").stats(category=StatCategory.PASSING)
for stat in leaders.stats[:3]:
    print(stat["name_display"], stat["pass_yds"], "yards", stat["pass_td"], "TDs")

# Get standings
standings = pfr.season("2023").standings()
for team in standings.AFC[:3]:
    print(team.team, team.wins, team.losses, team.points_diff)

# Get boxscore for Super Bowl LVIII
box = pfr.game("202402110kan").boxscore()
for t in box.teams:
    print(t.name, t.score)
print(box.game_info["vegas_line"])

# Get home drives for the same game
detail = pfr.game("202402110kan").details(table_id=GameTable.HOME_DRIVES)
for row in detail.data[:3]:
    print(row["drive_num"], row["end_event"], row["net_yds"])

# Search for a player and get their profile
for player in pfr.players.search(query="Tom Brady"):
    print(player.name, player.player_id)
    prof = player.profile()
    print(prof.name, prof.position, prof.college)
    break
