"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    fantasycalc.com API (fantasycalc_com_api)
ID:     5e9d9ba7-cf7a-4bb0-bc6a-1c6038981577
Engine: parse_sdk 0.2.0
Generated at: 2026-07-22T15:52:11.630051+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Ppr(str, enum.Enum):
    FULL = '1'
    HALF = '0.5'
    ZERO = '0'


class NumQbs(str, enum.Enum):
    ONE = '1'
    TWO = '2'


class NumTeams(str, enum.Enum):
    TEN = '10'
    TWELVE = '12'
    FOURTEEN = '14'


class Player(_Resource):
    id: int
    age: Optional[float]
    name: str
    team: Optional[str]
    mfl_id: Optional[str]
    college: Optional[str]
    espn_id: Optional[str]
    ffpc_id: Optional[str]
    birthday: Optional[str]
    position: str
    sleeper_id: Optional[str]
    fleaflicker_id: Optional[str]
    years_of_experience: Optional[int]
    _RESOURCE_NAME = 'Player'
    _KEY_FIELD = 'id'
    _FIELD_ALIASES = {'age': 'maybeAge', 'team': 'maybeTeam', 'mfl_id': 'mflId', 'college': 'maybeCollege', 'espn_id': 'espnId', 'ffpc_id': 'ffpcId', 'birthday': 'maybeBirthday', 'sleeper_id': 'sleeperId', 'fleaflicker_id': 'fleaflickerId', 'years_of_experience': 'maybeYoe'}

class Ranking(_Resource):
    tier: Optional[int]
    value: int
    player: Player
    overall_rank: int
    trend_30_day: int
    position_rank: int
    redraft_value: Optional[int]
    combined_value: Optional[int]
    trade_frequency: Optional[float]
    _RESOURCE_NAME = 'Ranking'
    _KEY_FIELD = None
    _FIELD_ALIASES = {'tier': 'maybeTier', 'overall_rank': 'overallRank', 'trend_30_day': 'trend30Day', 'position_rank': 'positionRank', 'redraft_value': 'redraftValue', 'combined_value': 'combinedValue', 'trade_frequency': 'maybeTradeFrequency'}

class TradeCount(_Resource):
    count: int
    _RESOURCE_NAME = 'TradeCount'
    _KEY_FIELD = None

class ImpliedTrade(_Resource):
    id: int
    date: str
    side1: str
    side2: str
    value: int
    num_qbs: int
    is_dynasty: bool
    _RESOURCE_NAME = 'ImpliedTrade'
    _KEY_FIELD = None
    _FIELD_ALIASES = {'num_qbs': 'numQbs', 'is_dynasty': 'isDynasty'}

class TradeHistory(_Resource):
    implied_values: List[ImpliedTrade]
    historical_values: List[HistoricalValue]
    _RESOURCE_NAME = 'TradeHistory'
    _KEY_FIELD = None
    _FIELD_ALIASES = {'implied_values': 'impliedValues', 'historical_values': 'historicalValues'}

class HistoricalValue(_Resource):
    date: str
    value: int
    _RESOURCE_NAME = 'HistoricalValue'
    _KEY_FIELD = None

class FantasyCalcRankingsCollection(_Collection):
    def list(self, ppr: Optional[Ppr | str] = None, num_qbs: Optional[NumQbs | str] = None, num_teams: Optional[NumTeams | str] = None, is_dynasty: Optional[bool] = None, include_adp: Optional[bool] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Ranking]:
        """
        Fetch comprehensive fantasy football rankings and player values for a given league format. Returns all ranked players sorted by overall rank, each with trade value, positional rank, trend data, and player metadata. Paginates as a single page containing the full ranking list.

        Args:
            ppr: PPR scoring format.
            num_qbs: Number of starting QBs.
            num_teams: Number of teams in the league.
            is_dynasty: Whether to fetch Dynasty (true) or Redraft (false) rankings.
            include_adp: Whether to include ADP data in the response.
        """
        _params: Dict[str, Any] = {}
        if ppr is not None: _params['ppr'] = ppr
        if num_qbs is not None: _params['num_qbs'] = num_qbs
        if num_teams is not None: _params['num_teams'] = num_teams
        if is_dynasty is not None: _params['is_dynasty'] = is_dynasty
        if include_adp is not None: _params['include_adp'] = include_adp
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_rankings', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Ranking', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class FantasyCalcTradeCountsCollection(_Collection):
    def get(self) -> TradeCount:
        """
        Get the total number of trades in the FantasyCalc database. Returns a single integer count representing the cumulative number of trades analyzed.
        """
        _params: Dict[str, Any] = {}
        
        _resp = self._api._request('GET', 'get_trade_count', _params)
        return _coerce(_resp, 'TradeCount', self, mode='return')

class FantasyCalcTradeHistoriesCollection(_Collection):
    def get(self, player_id: str, num_qbs: Optional[NumQbs | str] = None, is_dynasty: Optional[bool] = None) -> TradeHistory:
        """
        Fetch implied trade value history for a specific player. Returns historical daily values and a list of implied trade scenarios with the assets on each side. The player_id is available from get_rankings results as items[].player.id.

        Args:
            player_id: The unique numeric player ID from FantasyCalc (available in get_rankings results as items[].player.id).
            num_qbs: Number of starting QBs.
            is_dynasty: Dynasty (true) or Redraft (false).
        """
        _params: Dict[str, Any] = {}
        if num_qbs is not None: _params['num_qbs'] = num_qbs
        if player_id is not None: _params['player_id'] = player_id
        if is_dynasty is not None: _params['is_dynasty'] = is_dynasty
        
        _resp = self._api._request('GET', 'get_player_trades', _params)
        return _coerce(_resp, 'TradeHistory', self, mode='return')

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Player': Player,
    'Ranking': Ranking,
    'TradeCount': TradeCount,
    'ImpliedTrade': ImpliedTrade,
    'TradeHistory': TradeHistory,
    'HistoricalValue': HistoricalValue,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class FantasyCalc(_BaseAPI):
    """
    Provides real-time fantasy football player rankings, trade values, and statistics derived from thousands of actual trades. Supports multiple league formats including Dynasty, Redraft, Superflex, and various scoring settings.
    """
    SCRAPER_ID: ClassVar[str] = '5e9d9ba7-cf7a-4bb0-bc6a-1c6038981577'
    PINNED_VERSION: ClassVar[Optional[int]] = 4

    @property
    def rankings(self) -> 'FantasyCalcRankingsCollection':
        return FantasyCalcRankingsCollection(_api=self, _parent=None)

    @property
    def trade_counts(self) -> 'FantasyCalcTradeCountsCollection':
        return FantasyCalcTradeCountsCollection(_api=self, _parent=None)

    @property
    def trade_histories(self) -> 'FantasyCalcTradeHistoriesCollection':
        return FantasyCalcTradeHistoriesCollection(_api=self, _parent=None)

__all__ = [
    'FantasyCalc',
    'Player',
    'Ranking',
    'TradeCount',
    'ImpliedTrade',
    'TradeHistory',
    'HistoricalValue',
    'Ppr',
    'NumQbs',
    'NumTeams',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
