# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
from parse_apis.fantasycalc_com_api import FantasyCalc, Ppr, NumQbs, NumTeams

client = FantasyCalc()

# List rankings for a 10-team zero-PPR single-QB dynasty league
for ranking in client.rankings.list(ppr=Ppr.ZERO, num_qbs=NumQbs.ONE, num_teams=NumTeams.TEN, is_dynasty=True):
    print(ranking.overall_rank, ranking.player.name, ranking.player.position, ranking.value, ranking.trend_30_day)

# Get trade history for a specific player
trade_history = client.tradehistories.get(player_id="6170", num_qbs=NumQbs.TWO, is_dynasty=True)
for hv in trade_history.historical_values:
    print(hv.date, hv.value)
for trade in trade_history.implied_values:
    print(trade.side1, trade.side2, trade.value, trade.date)

# Get total trade count
tc = client.tradecounts.get()
print(tc.count)
