"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    keeptradecut.com API (keeptradecut_com_api)
ID:     52095a49-4d80-48b7-9495-40d7716e1e65
Engine: parse_sdk 0.2.0
Generated at: 2026-07-22T15:52:11.630857+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Scoring(str, enum.Enum):
    ONE_QB = 'oneqb'
    SUPERFLEX = 'superflex'


class Position(str, enum.Enum):
    QB = 'QB'
    RB = 'RB'
    TE = 'TE'
    WR = 'WR'
    ALL = 'all'


class PlayerNotFound(_ParseError):
    """
    Player slug does not match any known player
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'slug': 'slug'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, slug: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.slug = slug


class Trade(_Resource):
    id: int
    date: str
    teamOne: TradeTeam
    teamTwo: TradeTeam
    settings: TradeSettings
    _RESOURCE_NAME = 'Trade'
    _KEY_FIELD = 'id'

class Player(_Resource):
    age: float
    cut: int
    kept: int
    rank: int
    slug: str
    team: str
    value: int
    rookie: bool
    traded: int
    college: str
    playerID: int
    position: Position | str
    playerName: str
    overallTier: int
    overallTrend: int
    positionalRank: int
    positionalTier: int
    seasonsExperience: int
    _RESOURCE_NAME = 'Player'
    _KEY_FIELD = 'slug'

    @property
    def detail(self) -> 'PlayerDetailCollection':
        _stash = getattr(self, '_sub_detail', None)
        if _stash is None:
            _stash = PlayerDetailCollection(_api=self._api, _parent=self)
            object.__setattr__(self, '_sub_detail', _stash)
        return _stash

class PlayerDetailCollection(_Collection):
    def get(self, scoring: Optional[Scoring | Literal['oneqb', 'superflex']] = None) -> PlayerDetail:
        """
        Retrieve detailed information about a specific dynasty player including physical attributes, draft capital, and current trade value. The slug is the player's URL-safe identifier (e.g. 'josh-allen-365') available from the rankings endpoint.

        Args:
            scoring: Scoring format for values.
        """
        _params: Dict[str, Any] = {}
        if scoring is not None: _params['scoring'] = scoring
        _params['slug'] = self._parent.slug
        
        _resp = self._api._request('GET', 'get_player_details', _params)
        return _coerce(_resp, 'PlayerDetail', self, mode='return')

class TradeTeam(_Resource):
    place: int
    playerIds: List[str]
    _RESOURCE_NAME = 'TradeTeam'
    _KEY_FIELD = None

class PlayerDetail(_Resource):
    age: float
    cut: int
    kept: int
    rank: int
    slug: str
    team: str
    value: int
    number: int
    rookie: bool
    traded: int
    weight: int
    byeWeek: int
    college: str
    pickNum: int
    scoring: Scoring | str
    playerID: int
    position: Position | str
    draftYear: int
    pickRound: int
    heightFeet: int
    playerName: str
    startupAdp: float
    tradeCount: int
    overallTier: int
    heightInches: int
    overallTrend: int
    teamLongName: str
    positionalRank: int
    positionalTier: int
    seasonsExperience: int
    _RESOURCE_NAME = 'PlayerDetail'
    _KEY_FIELD = 'slug'

class TradeSettings(_Resource):
    ppr: int
    qBs: int
    tep: int
    teams: int
    platform: int
    _RESOURCE_NAME = 'TradeSettings'
    _KEY_FIELD = None

class KeepTradeCutTradesCollection(_Collection):
    def list(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Trade]:
        """
        Retrieve recent real trades from dynasty fantasy football leagues. Trades are sourced from Sleeper, MFL, and other platforms. Each trade shows the player IDs exchanged between two teams and the league settings. Player IDs correspond to playerID values from the rankings endpoint.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_recent_trades', _p)
            items = _extract_items(_resp, 'trades')
            return ([_coerce(_i, 'Trade', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class KeepTradeCutPlayersCollection(_Collection):
    def search(self, scoring: Optional[Scoring | Literal['oneqb', 'superflex']] = None, position: Optional[Position | Literal['QB', 'RB', 'TE', 'WR', 'all']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Player]:
        """
        Retrieve dynasty fantasy football player rankings with crowdsourced trade values. Results are ordered by rank (highest value first). Each player includes their current trade value, positional rank, tier, and keep/trade/cut vote counts. The ranking pool is the top 500 dynasty-relevant players.

        Args:
            scoring: Scoring format for values.
            position: Filter by position.
        """
        _params: Dict[str, Any] = {}
        if scoring is not None: _params['scoring'] = scoring
        if position is not None: _params['position'] = position
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_dynasty_rankings', _p)
            items = _extract_items(_resp, 'players')
            return ([_coerce(_i, 'Player', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)
    def get(self, slug: str) -> Player:
        """
        Retrieve detailed information about a specific dynasty player including physical attributes, draft capital, and current trade value. The slug is the player's URL-safe identifier (e.g. 'josh-allen-365') available from the rankings endpoint.

        Args:
            slug: Player URL slug from rankings (e.g. 'josh-allen-365', 'bijan-robinson-1414').
        """
        _params: Dict[str, Any] = {}
        if slug is not None: _params['slug'] = slug
        
        _resp = self._api._request('GET', 'get_player_details', _params)
        return _coerce(_resp, 'Player', self, mode='return')

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Trade': Trade,
    'Player': Player,
    'TradeTeam': TradeTeam,
    'PlayerDetail': PlayerDetail,
    'TradeSettings': TradeSettings,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class KeepTradeCut(_BaseAPI):
    """
    Access dynasty fantasy football player rankings, trade values, and recent trades from KeepTradeCut's crowdsourced platform.
    """
    SCRAPER_ID: ClassVar[str] = '52095a49-4d80-48b7-9495-40d7716e1e65'
    PINNED_VERSION: ClassVar[Optional[int]] = 1
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': PlayerNotFound}

    @property
    def trades(self) -> 'KeepTradeCutTradesCollection':
        return KeepTradeCutTradesCollection(_api=self, _parent=None)

    @property
    def players(self) -> 'KeepTradeCutPlayersCollection':
        return KeepTradeCutPlayersCollection(_api=self, _parent=None)

__all__ = [
    'KeepTradeCut',
    'Trade',
    'Player',
    'TradeTeam',
    'PlayerDetail',
    'TradeSettings',
    'Scoring',
    'Position',
    'PlayerNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
