# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.

"""Walkthrough: KeepTradeCut dynasty fantasy football rankings and trades."""
from parse_apis.keeptradecut_com_api import KeepTradeCut, Position, Scoring, PlayerNotFound

client = KeepTradeCut()

# Browse top superflex QB rankings
for player in client.players.search(position=Position.QB, scoring=Scoring.SUPERFLEX, limit=5):
    print(f"{player.rank}. {player.playerName} ({player.team}) - Value: {player.value}")

# Drill into a specific player for full details via sub-resource
top_player = client.players.search(scoring=Scoring.SUPERFLEX, limit=1).first()
if top_player:
    detail = top_player.detail.get(scoring=Scoring.SUPERFLEX)
    print(f"\n{detail.playerName}: {detail.college}, Round {detail.pickRound} Pick {detail.pickNum}")
    print(f"  Trade value: {detail.value}, Tier: {detail.overallTier}, ADP: {detail.startupAdp}")

# Fetch recent real trades
for trade in client.trades.list(limit=3):
    print(f"\nTrade {trade.id} ({trade.date}): Team1 sent {trade.teamOne.playerIds} for {trade.teamTwo.playerIds}")
    print(f"  League: {trade.settings.teams} teams, {trade.settings.qBs} QB, PPR={trade.settings.ppr}")

# Handle player-not-found gracefully
try:
    client.players.get(slug="nonexistent-player-9999")
except PlayerNotFound as exc:
    print(f"\nPlayer not found: {exc}")

print("\nExercised: players.search / player.detail.get / trades.list / players.get")
